### ISSUE TITLE
Non-global GoogleSigned

### ISSUE THREAD

**Issue by kijanawoodard** [ericnewton76/gmaps-api-net#37] opened 2015-09-11 21:44 UTC
While the Places API _requires_ an api key, Geocode _fails_ if you include one. 

Is it possible to assign an api key to each service individually?

**Comment by Sheepzez** [comment] 2015-09-30 21:17
It sounds like the Geocoding failing could be caused by the key you're using not being enabled to use the geocoding library? 

That's slightly besides the point, and I'm sure you've moved on from this issue by now, but you bring up a good point regarding assigning api keys individually.

Perhaps this could be achieved by having an overload for Service classes that allows for a GoogleSigned instance to passed in as a parameter. 

Any thoughts on this proposal, @ericnewton76 ?

**Comment by kijanawoodard** [comment] 2015-09-30 23:02
I did move on. :-p

Checking now, appears GeoLocation was enabled, but not GeoCoding. Google's api console is......not user friendly.

But anyway, It struck me as a little odd to have the static class handling the signing rather than passing something in to the desired services.

**Comment by awexfwex** [comment] 2016-03-17 03:47
+1 for non-static key assigning. It's a bizarre choice.

**Comment by ericnewton76** [comment] 2016-12-07 18:11
Underneath it all, individual keys can be assigned to each service.  The reason for static was because of convenience, where you'd set it on app startup and that handles 99% of the use case scenarios.

So more involved scenarios such as yours invites more documentation of the handling of the keys as above.

**Comment by richardthombs** [comment] 2017-07-20 12:32
#94 updates the service constructors so that a `GoogleSigned` can be passed in. If one is not provided, then the one configured by GoogleSigned.AssignAllServices will be used instead. Eg:

```c#
var key = new GoogleSigned("my-api-key");
var geocode = new GeocodingService(key);
var result = geocode.GetResponse(blah blah);
```

**Closed** 2017-07-21 09:46 UTC
